language: cpp

matrix:
  include:
    - os: linux
      services: docker
      # Add `env` here to select different distros? Looks like we'd need addtional "- os:" entries 
      # with env set as, e.g. "ubuntu", "centos". Using higher level env would also add these
      # to the osx builds!
      env: DOCKER_IMAGE=benmorgan/supernemo-ubuntu:3.0
      #    - os: linux
      #services: docker
      #env: distro=centos6
    - os: osx
      osx_image: xcode8.3
      compiler: clang
    # Add additional os/osx_image pairs here as required

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      docker pull $DOCKER_IMAGE
      docker run \
             -itd \
             -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
             --name falaise-docker $DOCKER_IMAGE
    elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      brew ls --versions
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew install ninja yaml-cpp; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then docker exec falaise-docker brew install yaml-cpp; fi


# What this shows is we end up in the source dir for the checkout.
script:
  - pwd
  - ls -larth
  - env
  - git status
  - git log -n2
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      docker exec falaise-docker $TRAVIS_BUILD_DIR/.travis/cibuild.sh
    elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      $TRAVIS_BUILD_DIR/.travis/cibuild.sh
    fi


