# All build envs are for C++
language: cpp

# Use matrix: to explicitly specify the builds
# - Linux: Singular VM with docker, one build for
#          each different image
# - macOS: One each per osx_image value.
#          Only latest Sierra for now.
matrix:
  include:
    - os: linux
      services: docker
      env: DOCKER_IMAGE=supernemo/falaise-ubuntu1604-base
    - os: linux
      services: docker
      env: DOCKER_IMAGE=supernemo/falaise-centos6-base
    - os: osx
      osx_image: xcode8.3
      compiler: clang

# In a C++ project, no clear convention on before_install vs install
# (Travis doesn't do anything automatically). Use it to:
# - Linux: start the base container
# - macOS: install brew packages
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      docker pull $DOCKER_IMAGE
      docker run \
             -itd \
             -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
             --name falaise-docker $DOCKER_IMAGE
    elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      brew install ninja yaml-cpp
    fi

# Run packaged script to configure, make, run tests
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      docker exec falaise-docker $TRAVIS_BUILD_DIR/.travis/cibuild.sh
    elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      $TRAVIS_BUILD_DIR/.travis/cibuild.sh
    fi


